version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    versioning-strategy: increase
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'build(deps)'
      prefix-development: 'build(deps-dev)'
    groups:
      dependencies:
        patterns:
          - '*'
        exclude-patterns:
          - '@types/eslint__js'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    commit-message:
      prefix: 'ci(action)'
      prefix-development: 'ci(dev-action)'
    groups:
      dependencies:
        patterns:
          - '*'
