name: commit-lint

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      - name: Commit lint
        # Dependabot sometimes makes some really long commit messages and I can't stop it
        continue-on-error: ${{ contains(github.event.pull_request.labels.*.name, 'dependencies') || github.actor == 'dependabot[bot]' }}
        uses: ahmadnassri/action-conventional-commit-lint@v2.1.9
        with:
          token: ${{ github.token }}
